name: "The new assignment 1 with staging parameter123456789"

on:
  push:
    branches: [main]
    tags:
      - "deploy-*"

jobs:
  deploy:
    name: Deploy-infra+app
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6  # or latest stable version
  

      - name: Get stage from tag
        id: stage
        run: echo "stage=${GITHUB_REF_NAME#deploy-}" >> $GITHUB_OUTPUT

      - name: Get config_url
        id: config
        run: echo "config_file_url=https://raw.githubusercontent.com/${{ github.repository }}/main/configs/${{ steps.stage.outputs.stage }}.json" >> $GITHUB_OUTPUT

      - name: Terraform init
        run: terraform -chdir=terraform init

      - name: Terraform apply
        run: |
          terraform -chdir=terraform apply \
            -auto-approve \
            -var-file=${{ steps.stage.outputs.stage }}.tfvars \
            -var="config_file_url=${{ steps.config.outputs.config_file_url }}"

